unique_ids:
  assets:
    Snipaste_2025-08-20_10-50-39.png: '1756537384708858441040533.4149'
    standard-page.html: 5S73PH2H3JV2MSCC7IZQN6IWTWAXECPT
    theme.css: HLEQ3FEWSPIK7EKA3JZZYKU2PXDJTQLB
  forms:
    nav: KM2FPQ6BEYUC2IPYH2JZZ67QZPB45GXA
  modules: {}
  scripts: {}
  server_modules: {}
